STRENGTH     = 'str'
DEXTERITY    = 'dex'
CONSTITUTION = 'con'
INTELLIGENCE = 'int'
WISDOM       = 'wis'
CHARISMA     = 'chr'

UNIT_SIZE_FINE       = "UNIT_SIZE_FINE"
UNIT_SIZE_DIMINUTIVE = "UNIT_SIZE_DIMINUTIVE"
UNIT_SIZE_TINY       = "UNIT_SIZE_TINY" 
UNIT_SIZE_SMALL      = "UNIT_SIZE_SMALL"
UNIT_SIZE_MEDIUM     = "UNIT_SIZE_MEDIUM"
UNIT_SIZE_LARGE      = "UNIT_SIZE_LARGE"
UNIT_SIZE_HUGE       = "UNIT_SIZE_HUGE"
UNIT_SIZE_GARGANTUAN = "UNIT_SIZE_GARGANTUAN"
UNIT_SIZE_COLOSSAL   = "UNIT_SIZE_COLOSSAL"

UNIT_SIZE_FINE_SIZE_MODIFIER       = 8
UNIT_SIZE_DIMINUTIVE_SIZE_MODIFIER = 4
UNIT_SIZE_TINY_SIZE_MODIFIER       = 2
UNIT_SIZE_SMALL_SIZE_MODIFIER      = 1
UNIT_SIZE_MEDIUM_SIZE_MODIFIER     = 0
UNIT_SIZE_LARGE_SIZE_MODIFIER      = -1
UNIT_SIZE_HUGE_SIZE_MODIFIER       = -2
UNIT_SIZE_GARGANTUAN_SIZE_MODIFIER = -4
UNIT_SIZE_COLOSSAL_SIZE_MODIFIER   = -8
